### PR TITLE
Feat: Add and edit user info

### LINKED ISSUE #4: Ability to handle user information for resume
Store the following information, with routes for adding and updating it.

- Name
- Phone Number (enforce international country code)
- Email Address

### LINKED ISSUE #12: Ability to reorder Experience, Education and Skill lists
Through the API, users can change the order of the individual lists independently.

Goal: A user can change the order that their Experience, Education and Skill sections are displayed.

Fellows should collaborate with the fellows contributing to the JavaScript project to agree a standard format. The same issue for the client can be found here: https://github.com/MLH-Fellowship/orientation-project-js/issues/5

### LINKED ISSUE #23: Edit existing Skill
Using a ```PUT``` request for the ```/resume/skill``` route, update an existing Skill using its index position as an ID. As part of this, you should write a test in ```test_pytest.py``` to show it works.

### PR DESCRIPTION
**Pull request by DeleMike**
Fixes #4 , ability to handle user information for resume, and closes #23

- Implemented user creation route
- Implemented edit user route
- Implemented test case for user creation.
- Implement edit skill route
- Implemented test case for edit skill
- Implemented a flow for the ability for a user to reorder Experience, Education, and Skill sections on their resume which closes #12. 

I and @marcusgchan discussed [here](https://github.com/MLH-Fellowship/orientation-project-python-23.SUM.B.1/issues/12#issuecomment-1605619235)

================================= To add a user =================================
POST - `localhost:5000/user`
payload: 
```
 {
   "name": "Max Doee",
   "phone": "+2348050790740",
   "email": "janedoe@example.com",
   "resume_order": "[1,2,3]"
   
 }
``` 

Expected response upon successful user creation
`STATUS CODE = 201`
```
{
  "body": {
    "email": "janedoe@example.com",
    "name": "Max Doee",
    "phone": "+2348050790740",
    "resume_order": "[1,2,3]"
  },
  "id": 2,
  "message": "User created successfully"
}
```

Expected response if a bad request is sent
`STATUS CODE = 400`
```
{
  "error": "Invalid request payload. Required fields are missing."
}
```

==================================== Get all users ================================
GET :  
`localhost:5000/user`
Response:
`STATUS CODE = 400`
``` 
[
  {
    "email": "akinfriday@example.com",
    "name": "Akin Friday",
    "phone": "+2348050780750",
    "resume_order": "[1,2,3]"
  }
]
```

================================= Edit a user =============================
PUT:  
`localhost:5000/user/{x}`
`where x = id of user`. For now, we use the position in the list, where 1 = first item in the list
payload:
``` 
 {
   "name": "James Doe",
   "phone": "+12124567890",
   "email": "jamesdoe@example.com",
   "resume_order": "[2,1,3]" 
 }
```

Expected response after a successful update operation
`STATUS CODE = 201`
```
{
  "body": {
    "email": "jamesdoe@example.com",
    "name": "James Doe",
    "phone": "+12124567890",
    "resume_order": "[2,1,3]"
  },
  "id": 0,
  "message": "User updated successfully"
}
```

Expected response after a failed update operation: The user does not exist
`STATUS CODE = 400`
```
{
  "message": "User with ID x does not exist"
}
```

### CODE REVIEW

**Comment by DeleMike** [comment]
@dtemir Kindly review, thanks!

**Comment by DeleMike** [comment]
@dtemir, this PR is ready for review

**Comment by dtemir** [comment]
good job! would you like to add a page to edit the existing skill (something that will call the endpoint you defined)? https://github.com/MLH-Fellowship/orientation-project-js-23.SUM.B.1/issues/12

**Comment by DeleMike** [comment]
Sure! The issue is I'm not really versed with React that is being used in the frontend and we have a week left to finish the project. However, If anyone's good at it, we can collaborate together to build it.

**Comment by DeleMike** [comment]
Sure!
However, If anyone's good with React, can we collaborate together to build it? We have a week left and I don't want any learning procedure to delay the project.

**Pull request merged**
